/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './features/landing/routes/index'
import { Route as OgImageDotpngRouteImport } from './features/landing/routes/og-image.png'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageDotpngRoute = OgImageDotpngRouteImport.update({
  id: '/og-image/png',
  path: '/og-image/png',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og-image/png': typeof OgImageDotpngRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og-image/png': typeof OgImageDotpngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/og-image/png': typeof OgImageDotpngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/og-image/png'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/og-image/png'
  id: '__root__' | '/' | '/og-image/png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OgImageDotpngRoute: typeof OgImageDotpngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image/png': {
      id: '/og-image/png'
      path: '/og-image/png'
      fullPath: '/og-image/png'
      preLoaderRoute: typeof OgImageDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OgImageDotpngRoute: OgImageDotpngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
