/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './features/social/routes/social'
import { Route as SignaturesRouteImport } from './features/signatures/routes/signatures'
import { Route as PresentationsRouteImport } from './features/presentations/routes/presentations'
import { Route as CareersRouteImport } from './features/careers/routes/careers'
import { Route as BlogRouteImport } from './features/blog/routes/blog'
import { Route as IndexRouteImport } from './features/landing/routes/index'
import { Route as CareersDotindexRouteImport } from './features/careers/routes/careers.index'
import { Route as BlogDotindexRouteImport } from './features/blog/routes/blog.index'
import { Route as Char123LangChar125DotogImageRouteImport } from './features/landing/routes/{-$lang}.og-image'
import { Route as CareersDotslugRouteImport } from './features/careers/routes/careers.$slug'
import { Route as BlogDotslugRouteImport } from './features/blog/routes/blog.$slug'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignaturesRoute = SignaturesRouteImport.update({
  id: '/signatures',
  path: '/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersDotindexRoute = CareersDotindexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const BlogDotindexRoute = BlogDotindexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const Char123LangChar125DotogImageRoute =
  Char123LangChar125DotogImageRouteImport.update({
    id: '/{-$lang}/og-image',
    path: '/{-$lang}/og-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareersDotslugRoute = CareersDotslugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CareersRoute,
} as any)
const BlogDotslugRoute = BlogDotslugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/presentations': typeof PresentationsRoute
  '/signatures': typeof SignaturesRoute
  '/social': typeof SocialRoute
  '/blog/$slug': typeof BlogDotslugRoute
  '/careers/$slug': typeof CareersDotslugRoute
  '/{-$lang}/og-image': typeof Char123LangChar125DotogImageRoute
  '/blog/': typeof BlogDotindexRoute
  '/careers/': typeof CareersDotindexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/presentations': typeof PresentationsRoute
  '/signatures': typeof SignaturesRoute
  '/social': typeof SocialRoute
  '/blog/$slug': typeof BlogDotslugRoute
  '/careers/$slug': typeof CareersDotslugRoute
  '/{-$lang}/og-image': typeof Char123LangChar125DotogImageRoute
  '/blog': typeof BlogDotindexRoute
  '/careers': typeof CareersDotindexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRouteWithChildren
  '/presentations': typeof PresentationsRoute
  '/signatures': typeof SignaturesRoute
  '/social': typeof SocialRoute
  '/blog/$slug': typeof BlogDotslugRoute
  '/careers/$slug': typeof CareersDotslugRoute
  '/{-$lang}/og-image': typeof Char123LangChar125DotogImageRoute
  '/blog/': typeof BlogDotindexRoute
  '/careers/': typeof CareersDotindexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/presentations'
    | '/signatures'
    | '/social'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/{-$lang}/og-image'
    | '/blog/'
    | '/careers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/presentations'
    | '/signatures'
    | '/social'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/{-$lang}/og-image'
    | '/blog'
    | '/careers'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/careers'
    | '/presentations'
    | '/signatures'
    | '/social'
    | '/blog/$slug'
    | '/careers/$slug'
    | '/{-$lang}/og-image'
    | '/blog/'
    | '/careers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRouteWithChildren
  PresentationsRoute: typeof PresentationsRoute
  SignaturesRoute: typeof SignaturesRoute
  SocialRoute: typeof SocialRoute
  Char123LangChar125DotogImageRoute: typeof Char123LangChar125DotogImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signatures': {
      id: '/signatures'
      path: '/signatures'
      fullPath: '/signatures'
      preLoaderRoute: typeof SignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersDotindexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogDotindexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/{-$lang}/og-image': {
      id: '/{-$lang}/og-image'
      path: '/{-$lang}/og-image'
      fullPath: '/{-$lang}/og-image'
      preLoaderRoute: typeof Char123LangChar125DotogImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersDotslugRouteImport
      parentRoute: typeof CareersRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogDotslugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogDotslugRoute: typeof BlogDotslugRoute
  BlogDotindexRoute: typeof BlogDotindexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogDotslugRoute: BlogDotslugRoute,
  BlogDotindexRoute: BlogDotindexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CareersRouteChildren {
  CareersDotslugRoute: typeof CareersDotslugRoute
  CareersDotindexRoute: typeof CareersDotindexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersDotslugRoute: CareersDotslugRoute,
  CareersDotindexRoute: CareersDotindexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRouteWithChildren,
  PresentationsRoute: PresentationsRoute,
  SignaturesRoute: SignaturesRoute,
  SocialRoute: SocialRoute,
  Char123LangChar125DotogImageRoute: Char123LangChar125DotogImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
